"use client";

import React from "react";
import toast from "react-hot-toast";
import { onAuthStateChanged } from "firebase/auth";
import { Check, Trash2 } from "lucide-react";
import {
  auth,
  deleteWorkspaceRecordById,
  getUserNotifications,
  markAllNotificationsAsRead,
  markNotificationAsRead,
  type UserNotification,
} from "@/lib/firebase";

const priorityClassMap: Record<UserNotification["priority"], string> = {
  high: "bg-red-500",
  medium: "bg-amber-500",
  low: "bg-emerald-500",
};

const formatDate = (value: UserNotification["createdAt"]) => {
  if (!value) {
    return "-";
  }

  return value.toDate().toLocaleString("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

export default function Page() {
  const [uid, setUid] = React.useState<string | null>(null);
  const [notifications, setNotifications] = React.useState<UserNotification[]>([]);

  const loadNotifications = React.useCallback(async (nextUid: string) => {
    try {
      const items = await getUserNotifications(nextUid);
      setNotifications(items);
    } catch (error) {
      toast.error("Failed to load notifications");
      console.error("Notification page load error:", error);
    }
  }, []);

  React.useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (!user) {
        setUid(null);
        setNotifications([]);
        return;
      }

      setUid(user.uid);
      void loadNotifications(user.uid);
    });

    return () => unsubscribe();
  }, [loadNotifications]);

  const handleReadOne = async (notificationId: string) => {
    if (!uid) {
      return;
    }

    try {
      await markNotificationAsRead(uid, notificationId);
      setNotifications((prev) =>
        prev.map((item) => (item.id === notificationId ? { ...item, isRead: true } : item)),
      );
    } catch (error) {
      toast.error("Failed to update notification");
      console.error("Read one notification error:", error);
    }
  };

  const handleReadAll = async () => {
    if (!uid) {
      return;
    }

    try {
      await markAllNotificationsAsRead(uid);
      setNotifications((prev) => prev.map((item) => ({ ...item, isRead: true })));
      toast.success("All notifications marked as read");
    } catch (error) {
      toast.error("Failed to mark all as read");
      console.error("Read all notifications error:", error);
    }
  };

  const handleDelete = async (notificationId: string) => {
    if (!uid) {
      return;
    }

    try {
      await deleteWorkspaceRecordById(uid, "notifications", notificationId);
      setNotifications((prev) => prev.filter((item) => item.id !== notificationId));
      toast.success("Notification removed");
    } catch (error) {
      toast.error("Failed to remove notification");
      console.error("Delete notification error:", error);
    }
  };

  return (
    <section className="rounded-2xl border border-outline bg-forground text-text">
      <div className="flex items-start justify-between gap-3 border-b border-outline px-5 py-4">
        <div>
          <h1 className="text-2xl font-semibold">Notifications</h1>
          <p className="mt-1 text-sm text-text-secondary">
            Review account and task alerts generated by your workspace actions.
          </p>
        </div>
        <button
          className="rounded-xl bg-text px-4 py-2 text-sm font-medium text-forground"
          onClick={() => void handleReadAll()}
          type="button"
        >
          Mark All Read
        </button>
      </div>

      <div className="divide-y divide-outline">
        {notifications.map((notification) => (
          <article className={`px-5 py-4 ${notification.isRead ? "opacity-70" : ""}`} key={notification.id}>
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0">
                <div className="flex items-center gap-2">
                  <span className={`h-2 w-2 rounded-full ${priorityClassMap[notification.priority]}`} />
                  <h2 className="text-base font-semibold">{notification.title}</h2>
                </div>
                <p className="mt-1 text-sm text-text-secondary">{notification.message}</p>
                <p className="mt-2 text-xs uppercase tracking-wide text-text-secondary">
                  {notification.taskType} • {formatDate(notification.createdAt)}
                </p>
              </div>

              <div className="flex items-center gap-2">
                {!notification.isRead && (
                  <button
                    className="inline-flex items-center gap-1 rounded-lg border border-outline px-2.5 py-1.5 text-xs font-medium text-text hover:bg-secondary"
                    onClick={() => void handleReadOne(notification.id)}
                    type="button"
                  >
                    <Check className="h-3.5 w-3.5" /> Read
                  </button>
                )}
                <button
                  className="inline-flex items-center gap-1 rounded-lg border border-outline px-2.5 py-1.5 text-xs font-medium text-text hover:bg-secondary"
                  onClick={() => void handleDelete(notification.id)}
                  type="button"
                >
                  <Trash2 className="h-3.5 w-3.5" /> Delete
                </button>
              </div>
            </div>
          </article>
        ))}

        {notifications.length === 0 && (
          <div className="px-5 py-10 text-center text-sm text-text-secondary">No notifications yet.</div>
        )}
      </div>
    </section>
  );
}